# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RPCtest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rRPCtest.proto\x12\x07myproto\"\x1a\n\nSumNumsREQ\x12\x0c\n\x04nums\x18\x01 \x01(\x05\"\x1c\n\nSumNumsACK\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32=\n\x03Sum\x12\x36\n\x08SayHello\x12\x13.myproto.SumNumsREQ\x1a\x13.myproto.SumNumsACK\"\x00\x42\x0bZ\t./myprotob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RPCtest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t./myproto'
  _SUMNUMSREQ._serialized_start=26
  _SUMNUMSREQ._serialized_end=52
  _SUMNUMSACK._serialized_start=54
  _SUMNUMSACK._serialized_end=82
  _SUM._serialized_start=84
  _SUM._serialized_end=145
# @@protoc_insertion_point(module_scope)
