# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import RPCtest_pb2 as RPCtest__pb2


class SumStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/myproto.Sum/SayHello',
                request_serializer=RPCtest__pb2.SumNumsREQ.SerializeToString,
                response_deserializer=RPCtest__pb2.SumNumsACK.FromString,
                )


class SumServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SumServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=RPCtest__pb2.SumNumsREQ.FromString,
                    response_serializer=RPCtest__pb2.SumNumsACK.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myproto.Sum', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sum(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myproto.Sum/SayHello',
            RPCtest__pb2.SumNumsREQ.SerializeToString,
            RPCtest__pb2.SumNumsACK.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
